name: CI

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        touch myfile.txt
        touch myfile2.txt
        echo "This is for showing something...."